// External dimensions are verified; small details and internal arrangements are approximations.
const intel='https://www.intel.com/content/www/us/en/products/sku/236773/intel-core-i9-processor-14900k-36m-cache-up-to-6-00-ghz/specifications.html';
export const CATALOG = {
  cpu:{name:'프로세서',en:'CENTRAL PROCESSING UNIT',model:'Intel Core i9-14900K',size:'37.5 × 45 mm',tag:'LGA1700',source:intel,description:'작은 금속 덮개 아래, 컴퓨터의 판단이 시작됩니다. 기판을 뒤집어 소켓과 맞닿는 금색 접점을 살펴보세요.',features:['니켈 도금 히트스프레더','LGA 접점 · 패키지 기판','분해 보기: 덮개와 다이'],verified:true},
  gpu:{name:'그래픽 카드',en:'GRAPHICS PROCESSING UNIT',model:'GeForce RTX 4090 · Founders Edition',size:'304 × 137 × 61 mm',tag:'PCIe ×16',source:'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4090/',description:'두꺼운 방열핀, 금속 프레임, 서로 반대 면의 팬. 실리콘이 만든 열을 바깥으로 내보내는 구조를 돌려 보세요.',features:['양면 팬 · 3슬롯 두께','알루미늄 프레임 · 방열핀','PCIe 접점 · I/O 브래킷'],verified:true},
  dram:{name:'메모리',en:'DYNAMIC RANDOM ACCESS MEMORY',model:'DDR5 UDIMM · 표준 기판',size:'133.35 × 31.25 mm',tag:'DDR5',source:'https://www.kingston.com/datasheets/KF556C40BW-32.pdf',description:'길고 얇은 기판 위에 여러 메모리 칩이 놓입니다. 아래쪽 금색 접점이 CPU와 데이터를 주고받는 통로입니다.',features:['표준 DIMM 기판 비율','양면 DRAM 패키지','금색 접점 · 전원 관리 칩'],verified:true},
  ssd:{name:'솔리드 스테이트 드라이브',en:'SOLID STATE DRIVE',model:'Samsung 990 PRO · M.2 2280',size:'80 × 22 × 2.3 mm',tag:'NVMe',source:'https://www.samsung.com/uk/memory-storage/nvme-ssd/990-pro-1tb-nvme-pcie-gen-4-mz-v9p1t0bw/',description:'손가락만 한 기판에 담긴 저장장치. 라벨을 들어 올려 컨트롤러와 NAND 플래시의 배치를 살펴보세요.',features:['M.2 2280 기판 · M-key','NAND · 컨트롤러 · DRAM','분해 보기: 제품 라벨'],verified:true},
  mainboard:{name:'메인보드',en:'MOTHERBOARD',model:'ASUS PRIME Z790-P · 외형 참고',size:'234 × 305 mm',tag:'ATX',source:'https://www.asus.com/es/motherboards-components/motherboards/prime/prime-z790-p/techspec/',description:'소켓, 메모리 슬롯, 확장 슬롯과 전원부가 한 기판 위에 연결됩니다. 부품이 놓이는 위치와 높이 차이를 살펴보세요.',features:['LGA 소켓 · DIMM 슬롯 4개','PCIe · M.2 · SATA','후면 I/O · VRM 방열판'],verified:true},
  cooling:{name:'쿨링 팬',en:'THERMAL MANAGEMENT',model:'Noctua NF-A12x25 PWM · 외형 참고',size:'120 × 120 × 25 mm',tag:'120 mm',source:'https://www.noctua.at/en/products/nf-a12x25-pwm/specifications',description:'사각 프레임 안에서 아홉 장의 날개가 공기를 움직입니다. 프레임의 두께와 모터 지지대까지 확인해 보세요.',features:['9엽 곡면 임펠러','프레임 · 모터 지지대','모서리 진동 방지 패드'],verified:true},
  hdd:{name:'하드 디스크 드라이브',en:'HARD DISK DRIVE',model:'Seagate BarraCuda · 3.5형 참고',size:'101.85 × 146.99 mm',tag:'SATA',source:'https://www.seagate.com/content/dam/seagate/migrated-assets/www-content/datasheets/pdfs/barracuda-pro-14-tb-DS1901-10-2006GB-en_EM.pdf',description:'밀폐된 금속 케이스 안에 회전하는 디스크가 있습니다. 분해 보기에서 커버를 열고 플래터와 헤드 암을 확인하세요.',features:['밀폐 커버 · 고정 나사','내부 플래터 · 스핀들','액추에이터 · SATA 커넥터'],verified:true},
  power:{name:'전원 공급 장치',en:'POWER SUPPLY UNIT',model:'ATX 파워서플라이 · 구조 모델',size:'150 × 140 × 86 mm',tag:'ATX PSU',description:'금속 섀시와 냉각 팬, 보호 그릴, 모듈러 커넥터로 이루어진 전원 공급 장치입니다.',features:['금속 섀시 · 팬 그릴','모듈러 커넥터','전원 사양 라벨']},
};
const extra={npu:['신경망 프로세서','NPU'],sram:['캐시 메모리','SRAM'],vram:['그래픽 메모리','VRAM'],spirom:['SPI 플래시','SOIC-8'],bus:['시스템 버스','PCIe SLOT'],display:['모니터','DISPLAY'],input:['키보드','KEYBOARD'],audio:['스피커','AUDIO'],camera:['웹캠','WEBCAM'],nic:['네트워크 카드','NIC'],infra:['라우터','ROUTER'],datacenter:['서버 랙','SERVER RACK'],coproc:['보조 프로세서','MCU'],vrm:['전원부','VRM'],mouse:['마우스','MOUSE']};
for(const [id,[name,en]] of Object.entries(extra))CATALOG[id]={name,en,model:`${name} · 대표 구조 모델`,size:'제품별 상이',tag:en,description:'외형과 연결 구조를 살펴보기 위한 대표 모델입니다. 특정 제조사 제품을 그대로 복제한 모델은 아닙니다.',features:['입체 형상 · 표면 재질','앞면과 뒷면 관찰','회전 · 확대 지원']};
export const ALIASES={ram:'dram',psu:'power',fan:'cooling',mon:'display',kb:'input',cam:'camera',spk:'audio',router:'infra',spi:'spirom',pch:'coproc',board:'mainboard',keyboard:'input'};
export function modelId(id){return ALIASES[id]||id;}
